# Generated by Django 6.0.5 on 2026-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('SUPPORT', 'Soporte'), ('IMPROVEMENT', 'Mejora'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
